/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_matt_patch_openapi_MergePatch */

#ifndef _Included_com_matt_patch_openapi_MergePatch
#define _Included_com_matt_patch_openapi_MergePatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_matt_patch_openapi_MergePatch
 * Method:    merge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_matt_patch_openapi_MergePatch_merge
		(JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
